export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      inquiries: {
        Row: {
          created_at: string;
          email: string;
          first_name: string;
          id: string;
          interest: string;
          last_name: string;
          message: string;
          note: string;
          object_ref: string;
          phone: string;
          status: string;
          updated_at: string;
        };
        Insert: {
          created_at?: string;
          email: string;
          first_name: string;
          id?: string;
          interest?: string;
          last_name: string;
          message: string;
          note?: string;
          object_ref?: string;
          phone?: string;
          status?: string;
          updated_at?: string;
        };
        Update: {
          created_at?: string;
          email?: string;
          first_name?: string;
          id?: string;
          interest?: string;
          last_name?: string;
          message?: string;
          note?: string;
          object_ref?: string;
          phone?: string;
          status?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      properties: {
        Row: {
          city: string;
          created_at: string;
          description: string[];
          energy: Json;
          equipment: string[];
          featured: boolean;
          features: Json;
          hero_note: string | null;
          id: string;
          images: string[];
          living_space: number;
          location: string;
          price: number;
          published: boolean;
          rooms: number;
          slug: string;
          sort_order: number;
          status: string;
          summary: string;
          title: string;
          updated_at: string;
        };
        Insert: {
          city: string;
          created_at?: string;
          description?: string[];
          energy?: Json;
          equipment?: string[];
          featured?: boolean;
          features?: Json;
          hero_note?: string | null;
          id?: string;
          images?: string[];
          living_space?: number;
          location?: string;
          price?: number;
          published?: boolean;
          rooms?: number;
          slug: string;
          sort_order?: number;
          status?: string;
          summary?: string;
          title: string;
          updated_at?: string;
        };
        Update: {
          city?: string;
          created_at?: string;
          description?: string[];
          energy?: Json;
          equipment?: string[];
          featured?: boolean;
          features?: Json;
          hero_note?: string | null;
          id?: string;
          images?: string[];
          living_space?: number;
          location?: string;
          price?: number;
          published?: boolean;
          rooms?: number;
          slug?: string;
          sort_order?: number;
          status?: string;
          summary?: string;
          title?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      reference_objects: {
        Row: {
          category: string;
          created_at: string;
          description: string[];
          equipment: string[];
          id: string;
          images: string[];
          living_space: number;
          location: string;
          parking: number | null;
          plot: number | null;
          published: boolean;
          region: string;
          rooms: number;
          slug: string;
          sort_order: number;
          summary: string;
          testimonial: Json | null;
          title: string;
          type_label: string;
          updated_at: string;
          year: number | null;
        };
        Insert: {
          category?: string;
          created_at?: string;
          description?: string[];
          equipment?: string[];
          id?: string;
          images?: string[];
          living_space?: number;
          location?: string;
          parking?: number | null;
          plot?: number | null;
          published?: boolean;
          region: string;
          rooms?: number;
          slug: string;
          sort_order?: number;
          summary?: string;
          testimonial?: Json | null;
          title: string;
          type_label?: string;
          updated_at?: string;
          year?: number | null;
        };
        Update: {
          category?: string;
          created_at?: string;
          description?: string[];
          equipment?: string[];
          id?: string;
          images?: string[];
          living_space?: number;
          location?: string;
          parking?: number | null;
          plot?: number | null;
          published?: boolean;
          region?: string;
          rooms?: number;
          slug?: string;
          sort_order?: number;
          summary?: string;
          testimonial?: Json | null;
          title?: string;
          type_label?: string;
          updated_at?: string;
          year?: number | null;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
